version: "3.8"

networks:
  sermatec:
    external: true

services:
  command-help:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - "-h"
    networks:
      - sermatec

  runner-client-only:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - "-dot-env-file=/secrets/application.env"
      - "--client"
    volumes:
      - ./application.env:/secrets/application.env:ro
    networks:
      - sermatec
